### ISSUE TITLE
Canvas scaling skwed 

### ISSUE THREAD

**Issue by kevinjos** [gl-vis/gl-plot3d#1]
Using the following code:

var createScene = require('gl-plot3d');
var scene = createScene({'canvas': document.getElementById('mycanvas')});

I expect the canvas to maintain it's height and width defined in html. This was the case in v1.0.0. However, when I try 1.0.1, adding the scene to the canvas results in a change in placement and dimension of the canvas.

**Comment by mikolalysenko** [comment]
yeah, this an issue with canvas-scale.  I could have some flag to control this maybe?

**Comment by mikolalysenko** [comment]
It should be fixed in the newest version.  You can pass a flag called autoResize to the scene object which will disable the default scaling behavior.
