### ISSUE TITLE
Hardware + chrome-dependent washed out colors

### ISSUE THREAD

**Issue by rreusser** [gl-vis/gl-plot3d#9]
If I visit this page: https://rreusser.github.io/plotly-mock-viewer/#gl3d_bunny

On a computer with these specs:
OS X El Capitan
Version 10.11.6
MacBook Pro (Retina, 13-inch, Early 2015)
Processor 2.7 GHz Intel Core i5
Memory 8 GB 1867 MHz DDR3
Graphics Intel Iris Graphics 6100 1536 MB

With Chrome 62.0.3202.94

I see this:
<img width="647" alt="screen shot 2017-12-08 at 2 52 02 pm" src="https://user-images.githubusercontent.com/572717/33788479-603c0774-dc27-11e7-9404-149c877695ba.png">

With Chrome <= 59, I see this:

<img width="598" alt="screen shot 2017-12-08 at 2 54 58 pm" src="https://user-images.githubusercontent.com/572717/33788548-d9897512-dc27-11e7-89f2-78a8faadc8cd.png">

If I change [scene.js#L706](https://github.com/gl-vis/gl-plot3d/blob/508ccc89b2648a19be87ecba74060c7f9d836281/scene.js#L706) to this:

```javascript
gl.clearColor(0,0,0,0.0000001)
```

I see this:

<img width="566" alt="screen shot 2017-12-08 at 2 57 19 pm" src="https://user-images.githubusercontent.com/572717/33788604-1bbd96b6-dc28-11e7-8ad4-94a6d9ff84c5.png">

I'm aware of this happening on other webgl software products and at least a couple computers using it. It seems like new Chrome has some sort of hardware-dependent bug.

**Comment by etpinard** [comment]
Good to know. Thanks!

Chrome 63 is getting [rolled out](https://chromereleases.googleblog.com/2017/12/stable-channel-update-for-desktop.html) in the coming days, so hopefully that will be enough to _solve_ the issue.

**Comment by rreusser** [comment]
Thanks. Yeah, best guess at the moment is that it's a hardware-dependent optimization that didn't exist before and which only fails on particular hardware so that they maybe just don't know about it. If I have time, I'll try to boil it down to a minimal reproduction.

**Comment by rreusser** [comment]
Managed to boil it down to a (reasonably) simple test case. Chromium bug report filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=794035

**Comment by rreusser** [comment]
Solution is: upgrade os x. It remained dependent upon the chrome version so I didn't expect it to be an os-level issue. Upgrading it fixed things though. Still might fail for people, but hopefully less and less over time. 🙈
